=== NataliaMarkova/courses/tourist_voucher.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="vouchers" type="VouchersType"/>

	<xs:complexType name="VouchersType">
		<xs:sequence>
			<xs:element name="voucher" minOccurs="1" maxOccurs="unbounded" type="RowType">
				<xs:unique name="VoucherID">
			        	<xs:selector xpath="voucher"/>
				        <xs:field xpath="@id" />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType> 	


	<xs:complexType name="RowType" mixed="true">
		<xs:sequence>
			<xs:element name="Type" type="VoucherType" />
			<xs:element name="Country" type="CountryType" />
			<xs:element name="Duration">
				<xs:complexType> 
					<xs:attribute name="days" type="DurationType"  use="required" />
					<xs:attribute name="nights" type="DurationType" use="required" />
				</xs:complexType> 
			</xs:element>
			<xs:element name="Transport" type="TransportType" />
			<xs:element name="Hotel">
				<xs:complexType>  
					<xs:sequence>
						<xs:element name="Facilities" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Facility" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="type" type="HotelType" use="optional" />
					<xs:attribute name="nutrition" type="NutritionType" use="required" />
					<xs:attribute name="room" type="xs:string" use="required"/>
				</xs:complexType> 
			</xs:element>
			<xs:element name="Cost">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Includes" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
  					</xs:sequence>
					<xs:attribute name="total" type="xs:decimal" use="required"/>
				</xs:complexType>
				<xs:unique name="FacilityName">
				       	<xs:selector xpath="Cost"/>
				        <xs:field xpath="@Includes" />
				</xs:unique> 
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />	
	</xs:complexType>


	<xs:simpleType name="VoucherType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Leisure"/>
			<xs:enumeration value="Treatment"/>
			<xs:enumeration value="Pilgrimage"/>
			<xs:enumeration value="Excursions"/>
			<xs:enumeration value="Shop tour"/>
		</xs:restriction>
	</xs:simpleType> 

	<xs:simpleType name="TransportType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Avia"/>
			<xs:enumeration value="Train"/>
			<xs:enumeration value="Bus"/>
			<xs:enumeration value="Ship"/>
		</xs:restriction>
	</xs:simpleType> 

	<xs:simpleType name="CountryType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]+( [a-zA-Z]+)*"/>
		</xs:restriction>
	</xs:simpleType> 

	<xs:simpleType name="DurationType">
		<xs:restriction base="xs:nonNegativeInteger">
	    		<xs:maxInclusive value="50"/>
		</xs:restriction>
	</xs:simpleType> 


	<xs:simpleType name="HotelType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\*{1,5}"/>
		</xs:restriction>
	</xs:simpleType> 

	<xs:simpleType name="NutritionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NM"/>
			<xs:enumeration value="BB"/>
			<xs:enumeration value="HB"/>
			<xs:enumeration value="AI"/>
			<xs:enumeration value="UAI"/>
		</xs:restriction>
	</xs:simpleType> 


</xs:schema>

=== NataliaMarkova/courses/tourist_voucher.xml
<?xml version="1.0" encoding="windows-1251" ?>

<vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tourist_voucher.xsd">
<!--<vouchers>-->
	<voucher id="1">
		<Type>Leisure</Type>
		<Country>Spain</Country>
		<Duration days="8" nights="7"/>
		<Transport>Avia</Transport>
		<Hotel name="Andalusian miracle" type="***" />
		<vch:Room xmlns:vch="http://www.markova.kiev.ua/epam_courses/project3"
				  type="double (standart)" nutrition="HB" >
			<vch:Facilities>
				<vch:Facility>Conditioner</vch:Facility>
				<vch:Facility>TV</vch:Facility>
			</vch:Facilities>
		</vch:Room>
		<Cost total="1000.00">
			<Includes>Transfer</Includes>
			<Includes>Flight</Includes>
			<Includes>Accomodation</Includes>
			<Includes>Nutrition</Includes>
		</Cost>
	</voucher>
	<voucher id="2">
		<Type>Leisure</Type>
		<Country>Spain</Country>
		<Duration days="10" nights="9"/>
		<Transport>Avia</Transport>
		<Hotel name="Bilbao miracle" type="***" />
		<vch:Room xmlns:vch="http://www.markova.kiev.ua/epam_courses/project3" type="4-bedrooms apartment" nutrition="NM" >
			<vch:Facilities>
				<vch:Facility>Conditioner</vch:Facility>
				<vch:Facility>TV</vch:Facility>
				<vch:Facility>Washing machine</vch:Facility>
				<vch:Facility>Swimming pool</vch:Facility>
			</vch:Facilities>
		</vch:Room>
		<Cost total="3000.00">
			<Includes>Flight</Includes>
			<Includes>Accommodation</Includes>
		</Cost>
	</voucher>
</vouchers>
